name: wiggli_test
description: "A new Flutter project."
publish_to: 'none'  
 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.4.6
  hooks_riverpod: ^2.4.6
  gen_i18n: ^1.0.3 
  flutter_gen_runner: ^5.3.2
  dartz: ^0.10.1
  cached_network_image: ^3.3.0
  flutter_localizations:
    sdk: flutter
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  flash: ^3.0.5+2
  persistent_bottom_nav_bar: ^5.0.2
  salomon_bottom_bar: ^3.3.2
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  flutter_point_tab_bar: ^0.2.0
  sliding_clipped_nav_bar: ^3.1.0+4
  dot_navigation_bar: ^1.0.2
  freezed: ^2.4.5
  flutter_hooks: ^0.20.3
  logger: ^2.0.2+1
  dotted_line: ^3.2.2
  fluttertoast: ^8.2.4
  flutter_native_splash: ^2.3.5


flutter_gen:
  assets:
    enabled: true 
  integrations:
    flutter_svg: true
    lottie: true  

dev_dependencies:
  flutter_test:
    sdk: flutter
    
 
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1 
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
   
 
flutter:
 
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/ 
    - assets/json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
